import { generateSlug } from "random-word-slugs";

function SlugGenerator(difficulty) {
  console.log(`SlugGenerator called with difficulty: ${difficulty}`);

  let phrase;
  if (difficulty === "easy") {
    console.log("Generating an easy phrase...");
    phrase = generateSlug(1, {
      format: "title",
      partsOfSpeech: ["noun"],
      categories: {
        adjective: [],
        noun: ["animals", "food"],
      },
    });
  } else if (difficulty === "medium") {
    console.log("Generating a medium phrase...");
    phrase = generateSlug(2, {
      format: "title",
      partsOfSpeech: ["adjective", "noun"],
      categories: {
        adjective: ["color"],
        noun: ["animals", "food", "transportation"],
      },
    });
  } else {
    console.log("Generating a hard phrase...");
    phrase = generateSlug(3, {
      format: "title",
      partsOfSpeech: ["adjective", "adjective", "noun"],
      categories: {
        adjective: ["color", "shape"],
        noun: ["animals", "food", "transportation", "people"],
      },
    });
  }

  console.log(`Phrase generated by SlugGenerator: ${phrase}`);
  return phrase;
}

export default SlugGenerator;
